spring:
  application:
    name: identity-service
  datasource:
    url: jdbc:mysql://mysql:3306/nexus
    username: nexus_user
    password: ${NEXUS_MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      show-sql: true
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

server:
  port: 8881

jwt:
  secret: ${NEXUS_JWT_SECRET}
  expiration: 86400000
  refresh-expiration: 86400000

stripe:
  secret-key: ${STRIPE_SECRET_KEY}
  monthly-price-id: ${STRIPE_MONTHLY_PRICE}
  yearly-price-id: ${STRIPE_YEARLY_PRICE}

frontend-domain: ${FRONTEND_DOMAIN}

logging:
  level:
    com.nexus.identityservice: DEBUG # tus paquetes
    org.springframework.web: DEBUG # peticiones HTTP entrantes
    org.springframework.web.servlet.mvc.method.annotation: TRACE # más detalle
