sonar.projectName=Nexus
sonar.sourceEncoding=UTF-8

sonar.sources=services,webapp
sonar.tests=services,webapp
sonar.test.inclusions=**/*.spec.ts,**/*.test.ts,**/*.e2e-spec.ts,**/cypress/**/*.ts

sonar.exclusions=**/node_modules/**,**/dist/**,**/build/**,**/coverage/**,**/.next/**,**/.ionic/**,**/target/**,**/mvnw,**/mvnw.cmd,**/database/migrations/**,**/postman/**
sonar.coverage.exclusions=webapp/**,services/identity-service/**,services/compliance-service/**,services/trading-service/database/**,services/market-service/database/**,services/market-service/scripts/**,services/portfolio-service/scripts/**,services/portfolio-service/src/valuations/clients/**,services/portfolio-service/src/positions/repositories/**,services/portfolio-service/src/common/tracing/**,**/main.ts,**/*.module.ts,**/dto/**,**/entities/**,**/controllers/**
sonar.cpd.exclusions=**/*.spec.ts,**/*.e2e-spec.ts,**/*.test.ts,**/database/migrations/**,**/postman/**
sonar.javascript.lcov.reportPaths=services/trading-service/coverage/lcov.info,services/market-service/coverage/lcov.info,services/portfolio-service/coverage/lcov.info

sonar.typescript.tsconfigPaths=webapp/tsconfig.json,services/trading-service/tsconfig.json,services/portfolio-service/tsconfig.json,services/market-service/tsconfig.json,services/compliance-service/tsconfig.json
sonar.java.binaries=services/identity-service/target/classes
