sonar.projectName=Nexus
sonar.sourceEncoding=UTF-8

sonar.sources=services,webapp
sonar.tests=services,webapp
sonar.test.inclusions=**/*.spec.ts,**/*.test.ts,**/*.e2e-spec.ts,**/cypress/**/*.ts

sonar.exclusions=**/node_modules/**,**/dist/**,**/build/**,**/coverage/**,**/.next/**,**/.ionic/**,**/target/**,**/mvnw,**/mvnw.cmd
sonar.coverage.exclusions=**/*

sonar.typescript.tsconfigPaths=webapp/tsconfig.json,services/trading-service/tsconfig.json,services/portfolio-service/tsconfig.json,services/market-service/tsconfig.json,services/compliance-service/tsconfig.json
sonar.java.binaries=services/identity-service/target/classes
