package com.nexus.identityservice.exception;

import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.security.core.userdetails.UsernameNotFoundException;
import org.springframework.web.bind.MethodArgumentNotValidException;
import org.springframework.web.bind.annotation.ExceptionHandler;
import org.springframework.web.bind.annotation.RestControllerAdvice;

import java.util.HashMap;
import java.util.Map;

@RestControllerAdvice
public class GlobalExceptionController {

    @ExceptionHandler({
            NotFoundResourceException.class,
            UsernameNotFoundException.class
    })
    public ResponseEntity<Object> handleNotFoundResource(RuntimeException ex) {
        Map<String, Object> body = new HashMap<>();
        body.put("error", "Not Found Resource");
        body.put("message", ex.getMessage());
        return new ResponseEntity<>(body, HttpStatus.NOT_FOUND);
    }

    @ExceptionHandler(UserBannedException.class)
    public ResponseEntity<Object> handleUserBanned(UserBannedException ex) {
        Map<String, Object> body = new HashMap<>();
        body.put("error", "User Banned");
        body.put("message", ex.getMessage());
        body.put("retryAfter", 600); 
        return new ResponseEntity<>(body, HttpStatus.TOO_MANY_REQUESTS);
    }

    @ExceptionHandler({
            DuplicateResourceException.class
    })
    public ResponseEntity<Object> handleDuplicateResource(DuplicateResourceException ex) {
        Map<String, Object> body = new HashMap<>();
        body.put("error", "Duplicate Resource");
        body.put("message", ex.getMessage());
        return new ResponseEntity<>(body, HttpStatus.CONFLICT);
    }

    /**
     * Handles exceptions generated by data validation failures
     * using Bean Validation.
     *
     * @param ex exception of type {@link MethodArgumentNotValidException}
     * @return HTTP response with validation errors and status
     *         {@code 400 Bad Request}
     */
    // Bean Validation validations
    @ExceptionHandler(MethodArgumentNotValidException.class)
    public ResponseEntity<Object> handleValidationErrors(MethodArgumentNotValidException ex) {
        Map<String, String> errors = new HashMap<>();
        ex.getBindingResult().getFieldErrors().forEach(err -> errors.put(err.getField(), err.getDefaultMessage()));
        return new ResponseEntity<>(errors, HttpStatus.BAD_REQUEST);
    }

    @ExceptionHandler(Exception.class)
    public ResponseEntity<?> handleGeneral(Exception ex) {
        Map<String, Object> body = new HashMap<>();
        body.put("error", "ERROR");
        body.put("message", ex.getMessage());
        return new ResponseEntity<>(body, HttpStatus.INTERNAL_SERVER_ERROR);
    }
}
