$ErrorActionPreference = "Stop"

$scriptDirectory = Split-Path -Parent $MyInvocation.MyCommand.Path
$repositoryRoot = Resolve-Path (Join-Path $scriptDirectory "../..")
$envFile = Join-Path $scriptDirectory ".env"
$composeFile = Join-Path $scriptDirectory "docker-compose.yml"

function New-LocalSecret {
  param (
    [string] $Prefix
  )

  $bytes = New-Object byte[] 32
  $randomGenerator = [System.Security.Cryptography.RandomNumberGenerator]::Create()

  try {
    $randomGenerator.GetBytes($bytes)
    $randomValue = [Convert]::ToBase64String($bytes)
  } finally {
    $randomGenerator.Dispose()
  }

  return "$Prefix-$randomValue".Replace("=", "").Replace("+", "").Replace("/", "")
}

if (-not (Test-Path $envFile)) {
  $envContent = @(
    "# Generated by infrastructure/docker/start-local.ps1"
    "# This file is intentionally ignored by Git."
    "NEXUS_MYSQL_ROOT_PASSWORD=$(New-LocalSecret "mysql-root")"
    "NEXUS_MYSQL_PASSWORD=$(New-LocalSecret "mysql-app")"
    "NEXUS_JWT_SECRET=$(New-LocalSecret "jwt")"
    "NEXUS_ADMIN_PASSWORD=$(New-LocalSecret "admin")"
  )

  Set-Content -Path $envFile -Value $envContent
  Write-Host "Created local Docker environment file at $envFile"
} else {
  Write-Host "Using existing local Docker environment file at $envFile"
}

Push-Location $repositoryRoot
try {
  docker compose --env-file $envFile -f $composeFile up -d --build
} finally {
  Pop-Location
}
