CREATE TABLE IF NOT EXISTS market_quotes (
  symbol VARCHAR(16) PRIMARY KEY,
  price DECIMAL(18, 6) NOT NULL,
  bid DECIMAL(18, 6) NOT NULL,
  ask DECIMAL(18, 6) NOT NULL,
  spread DECIMAL(18, 6) NOT NULL,
  currency VARCHAR(8) NOT NULL,
  provider VARCHAR(40) NOT NULL,
  as_of TIMESTAMP NOT NULL,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS market_quote_history (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  symbol VARCHAR(16) NOT NULL,
  price DECIMAL(18, 6) NOT NULL,
  bid DECIMAL(18, 6) NOT NULL,
  ask DECIMAL(18, 6) NOT NULL,
  spread DECIMAL(18, 6) NOT NULL,
  currency VARCHAR(8) NOT NULL,
  provider VARCHAR(40) NOT NULL,
  as_of TIMESTAMP NOT NULL,
  recorded_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_market_quote_history_symbol_as_of (symbol, as_of)
);

CREATE TABLE IF NOT EXISTS market_data_sync_events (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  status ENUM('SUCCESS', 'PARTIAL_FAILURE', 'FAILED') NOT NULL,
  provider VARCHAR(40) NOT NULL,
  requested_by VARCHAR(120) NOT NULL,
  symbols_count INT UNSIGNED NOT NULL,
  updated_count INT UNSIGNED NOT NULL,
  failed_count INT UNSIGNED NOT NULL,
  message VARCHAR(255) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
